import { useState } from "react";
import ProductListItem from "../FeaturedProducts/ProductListItem";

const useProduct = () => {
	const [products, setProducts] = useState();
	const [productsList, setProductsList] = useState();
	const mount = "https://allmightyccg.herokuapp.com/api/v1";

	/*
	///////////
	USED FOR SENDING QUERIES TO THE SERVER AND OBTAINING PRODUCTS

	DEFAULT SETTING IS FIRST PAGE WITH 25 ITEM LIMIT AND NO PRODUCTS FILTERED
	///////////
	*/
	const getAllProducts = async (page = 1, limit = 25, category = null) => {
		const queryFilter = category ? `&category${category}` : "";
		const products = await fetch(
			`${mount}/products?&page=${page}&limit=${limit}${queryFilter}`,
			{
				headers: {
					"Content-Type": "application/json",
				},
				method: "GET",
			}
		);
		const { data, pages } = await products.json();
		setProducts(data);
		return { data, pages };
	};

	//GENERATES THE JSX FOR THE ITEMS RETURNED BY QUERIES
	const getProductList = (product) => {
		const productList = product.map((cards) => {
			const { name, img, price, text, extension, _id } = cards;
			return (
				<ProductListItem
					productName={name}
					key={_id}
					src={img}
					productPrice={price}
					text={text}
					extension={extension}
				/>
			);
		});
		setProductsList(productList);
		return productList;
	};

	/* 
? NOTES ON RETURNED ITEMS
/////////////////////////////////////////////////////////////////
* products: Holds the raw data returned by the query.
* productList: Holds the JSX list generated by 'getProductsList'
/////////////////////////////////////////////////////////////////
*/

	return {
		products,
		productsList,
		getProductList,
		getAllProducts,
	};
};

export default useProduct;
